### PR TITLE
Clean code & support ES6

### PR DESCRIPTION
**Pull request by EcutDavid**

### CODE REVIEW

**Comment by kenshinji** [comment]
@EcutDavid There is one problem that you've replaced `page.js` with `pageSrc.js`, however you haven't changed the reference from `page.html`.

**UPDATE**
Ah, `page.js` is compiled from `pageSrc.js`, I see.

**Comment by kenshinji** [comment]
@EcutDavid Another question is if the extension is running within Chrome, so I think the latest Chrome has supported ES2015. Anyway, using Babel is good for backwards compatibility.

**Comment by kenshinji** [comment]
After stopping `npm run watchDev`, we have to consider how to exclude the unnecessary directories generated and package it into an runnable Chrome Extension. How about [this](https://github.com/oncletom/crx) npm package?

**Comment by EcutDavid** [comment]
Hmm... can you give me some link about how to upload extensions in Chrome store?  
Just upload the zip or?

**Comment by kenshinji** [comment]
@EcutDavid [This](http://stackoverflow.com/questions/24577024/install-chrome-extension-not-in-the-store) might help. We don't have to upload it to Chrome store to install it on Chrome. Just load the unpacked directory is okay though. However we wish there are more ways to install it.

**Comment by EcutDavid** [comment]
Ah, I mean what's in the directory is only matters when uploading to Chrome store......  
Not sure is there anything like [npmignore](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package)

**Pull request closed without merging**
